services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: sendmedia_bot:latest
    container_name: sendmedia_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
